name: Continuos Integretaion Delivery with gitHub

on:
  push:
    branches:
    - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: |
          cd 05_DockerizingOurJavaApp/00_BeforeDockerization/rest-with-spring-boot-and-java-erudio
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACESS_TOKEN }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd 05_DockerizingOurJavaApp/00_BeforeDockerization/rest-with-spring-boot-and-java-erudio
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-docker .
          
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-docker
      
      - name: Tag and Push Docker image to Amazon ECR
        env:
          IMAGE_TAG: latest
        run: |
          cd 05_DockerizingOurJavaApp/00_BeforeDockerization/rest-with-spring-boot-and-java-erudio

          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-docker:latest ${{ secrets.IMAGE_REPO_URL }}:$IMAGE_TAG

          docker push ${{ secrets.IMAGE_REPO_URL }}:$IMAGE_TAG
        
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ secrets.IMAGE_REPO_URL }}:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.SERVICE_NAME }}
          cluster: ${{ secrets.CLUSTER_NAME }}
          wait-for-service-stability: true